//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materia()
        {
            this.Grupoes = new HashSet<Grupo>();
        }
    
        public int IdMateria { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public decimal Costo { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IdSemestre { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual Semestre Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupo> Grupoes { get; set; }
    }
}
